Repository openshift-kni/telco-reference, pull requests merged in 2024-11, with the labels that each got.

#53 Fix name of CR
  telco-hub/configuration/reference-crs/optional/odf-internal/storageCluster.yaml
Labels: lgtm, approved

#55 Clean up reference CRs
  Makefile
  telco-hub/configuration/reference-crs/optional/logging/clusterLogging.yaml
  telco-hub/configuration/reference-crs/optional/lso/lsoLocalVolumeSet.yaml
  telco-hub/configuration/reference-crs/optional/lso/lsoNS.yaml
  telco-hub/configuration/reference-crs/optional/lso/lsoOperatorGroup.yaml
  telco-hub/configuration/reference-crs/optional/lso/lsoSubscription.yaml
  telco-hub/configuration/reference-crs/optional/odf-internal/storageCluster.yaml
  telco-hub/configuration/reference-crs/optional/quay/quayNS.yaml
  telco-hub/configuration/reference-crs/optional/quay/quayOperatorGroup.yaml
  telco-hub/configuration/reference-crs/optional/quay/quaySubscription.yaml
  telco-hub/configuration/reference-crs/required/acm/acmAgentServiceConfig.yaml
  telco-hub/configuration/reference-crs/required/acm/acmMCH.yaml
  telco-hub/configuration/reference-crs/required/acm/acmNS.yaml
  telco-hub/configuration/reference-crs/required/acm/acmOperGroup.yaml
  telco-hub/configuration/reference-crs/required/acm/acmProvisioning.yaml
  telco-hub/configuration/reference-crs/required/acm/acmSubscription.yaml
  telco-hub/configuration/reference-crs/required/acm/observabilityMCO.yaml
  telco-hub/configuration/reference-crs/required/acm/observatilityNS.yaml
  telco-hub/configuration/reference-crs/required/talm/talmSubscription.yaml
  telco-hub/install/agent-config.yaml
  telco-hub/install/install-config.yaml
Labels: lgtm, approved

#60 Add README for telco ran DU use case
  telco-ran/README.md
Labels: lgtm, approved

#58 Update acmMCH.yaml
  telco-hub/configuration/reference-crs/optional/logging/clusterLogging.yaml
  telco-hub/configuration/reference-crs/optional/lso/lsoLocalVolume.yaml
  telco-hub/configuration/reference-crs/required/acm/acmMCH.yaml
Labels: lgtm, ok-to-test, approved

#56 Add GitOps CRs
  telco-hub/configuration/reference-crs/required/gitops/argocd-ssh-known-hosts-cm.yaml
  telco-hub/configuration/reference-crs/required/gitops/get_ztp_installation.sh
  telco-hub/configuration/reference-crs/required/gitops/gitopsNS.yaml
  telco-hub/configuration/reference-crs/required/gitops/gitopsOperatorGroup.yaml
  telco-hub/configuration/reference-crs/required/gitops/gitopsSubscription.yaml
  telco-hub/configuration/reference-crs/required/gitops/readme.md
  telco-hub/configuration/reference-crs/required/gitops/ztp-installation/app-project.yaml
  telco-hub/configuration/reference-crs/required/gitops/ztp-installation/argocd-openshift-gitops-patch.json
  telco-hub/configuration/reference-crs/required/gitops/ztp-installation/clusters-app.yaml
  telco-hub/configuration/reference-crs/required/gitops/ztp-installation/gitops-cluster-rolebinding.yaml
  telco-hub/configuration/reference-crs/required/gitops/ztp-installation/gitops-policy-rolebinding.yaml
  telco-hub/configuration/reference-crs/required/gitops/ztp-installation/kustomization.yaml
  telco-hub/configuration/reference-crs/required/gitops/ztp-installation/manifests.ver
  telco-hub/configuration/reference-crs/required/gitops/ztp-installation/policies-app-project.yaml
  telco-hub/configuration/reference-crs/required/gitops/ztp-installation/policies-app.yaml
  telco-hub/configuration/reference-crs/required/gitops/ztp-repo.yaml
Labels: lgtm, approved

#50 update sctp mc
  telco-core/configuration/reference-crs/optional/other/sctp_module_mc.yaml
Labels: lgtm, ok-to-test, approved

#41 [release-4.16] OCPBUGS-42504: Manual backport of Cluster Logging 6 CRs
  telco-core/configuration/reference-crs/optional/logging/ClusterLogForwarder.yaml
  telco-core/configuration/reference-crs/optional/logging/ClusterLogServiceAccount.yaml
  telco-core/configuration/reference-crs/optional/logging/ClusterLogServiceAccountAuditBinding.yaml
  telco-core/configuration/reference-crs/optional/logging/ClusterLogServiceAccountInfrastructureBinding.yaml
  telco-core/configuration/reference-crs/optional/logging/ClusterLogSubscription.yaml
  telco-core/configuration/reference-crs/optional/logging/ClusterLogging.yaml
Labels: lgtm, approved

#61 Add OWNERS file to branch release-4.16
  OWNERS
Labels: lgtm

#59 disable cluster-proxy-addon
  telco-hub/configuration/reference-crs/required/acm/disable-cluster-proxy-addon.json
  telco-hub/configuration/reference-crs/required/acm/readme.md
Labels: lgtm, approved

#63 ACM MCH obs CR configured with storage
  telco-hub/configuration/reference-crs/required/acm/observabilityMCO.yaml
Labels: lgtm, approved
